accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/', views.article_detail, name="detail"),
]

diplonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from . import views
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('about/', views.about),
    path('', article_views.article_list, name="home"),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    title = models.CharField(max_length=100)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.author)
    

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'image']

class CreateComment(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['title', 'body']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)

            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from .models import Article
from . import forms


def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})

@login_required(login_url="/accounts/login/")
def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    comments = article.comments.filter(active=True)
    newComment = None
    if request.method == 'POST':
        form = forms.CreateComment(request.POST, request.FILES)
        if form.is_valid():
            newComment = form.save(commit=False)
            newComment.article = article
            newComment.author = request.user
            newComment.save()
    else:
        form = forms.CreateComment()
    return render(request, 'articles/article_detail.html', {
        'article': article,
        'comments': comments,
        'newComment': newComment,
        'form': form
    })

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            formInstance = form.save(commit=False)
            formInstance.author = request.user
            formInstance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()        
    return render(request, 'articles/article_create.html', {'form': form})

diplonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

def about(request):
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container center">
    <h1>Login</h1>
    <div class="signup-form container light-blue darken-1 z-depth-5">
        <form class="site-form" action="{% url 'accounts:login' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
            {% endif %}
            <div class="submit-container">
                <button type="submit" value="Login" class="btn grey darken-4 center">Login</button> 
            </div>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container center">
    <h1>Signup</h1>
    <div class="signup-form container light-blue darken-1 z-depth-5">
        <form class="site-form" action="/accounts/signup/" method="POST">
            {% csrf_token %}
            {{ form }}
            <div class="submit-container">
                <button type="submit" value="Signup" class="btn grey darken-4 center">Signup</button> 
            </div>  
        </form>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
<section class="creation-form">
    <div class="create-article container light-blue darken-1 z-depth-5">
        <h2 class="center">Create an Awesome New Article!</h2>
        <form class="site-form container" action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Create" class="btn grey darken-4">
        </form>
    </div>
</section>
<script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="article-detail">
        <div class="article center">
            <img src="{{ article.image.url }}" alt="" class="responsive-img article-image">
            <div class="container center">
                <h1>{{article.title}}</h1>
                <p>{{article.body}}</p>
                <span>{{article.date}}</span>
                <p class="light-blue-text text-darken-1 flow-text">Added by {{ article.author.username }}</p>
            </div>
        </div>
    </div>
    <section class="comments-section">
        <div class="comments-container container center">
            <h3>Comments</h3>
            {% for comment in comments %}
            <div class="card comments light-blue z-depth-5">
                <div class="card-contents">
                    <p class="comment-title">{{ comment.title }}</p>
                    <span class="comment-body">{{ comment.body }}</span>
                    <p class="comment-info">Created by {{ comment.author }}, {{ comment.date }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="new-comment container center">
            {% if newComment %}
            <div class="alert alert-success flow-text light-blue-text text-darken-1" role="alert">
                Your comment is awaiting moderation
            </div>
            {% else %}
            <h3>Leave a comment</h3>
            <div class="form-container grey darken-4 z-depth-5">
                <form class="comment-form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn waves-effect waves-light btn light-blue darken-1">Submit</button>
                </form>
            </div>
            {% endif %}
        </div>
    </section>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
    <div class="container amber darken-3 center">
        <img src="{% static 'logo.jpg' %}" alt="logo" class="main-logo">
        <h1 class="grey-text text-lighten-5">Diplonautic</h1>
        <p class="flow-text">The oasis of opinions where the dinosaurs of gaming gather...</p>
    </div>
    <div class="container center">
        <h3>Article List</h3>
        <div class="row">
            {% for article in articles %}
            <div class="col s12 m6 l4">
                <div class="card grey darken-4 z-depth-5">
                    <div class="card-content">
                        <h4><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h4>
                        <p class="white-text">{{ article.snippet }}</p>
                        <span class="white-text date">{{ article.date }}</span>
                        <p class="light-blue darken-1 author">added by {{ article.author.username }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

templates/about.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <h1>About Us</h1>
    <p>We like Django</p>
</body>
</html>

templates/base_layout.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <!-- favicon and title -->
    <link rel="icon" href="./assets/img/diplodocus_white.ico" type="image/x-icon">
    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="navbar-fixed">
        <nav class="nav-wrapper grey darken-4">
            <div class="container">
                <a href="{% url 'home' %}" class="brand-logo"><img src="{% static 'logo_nav.jpg' %}" alt="logo" class="responsive-img nav-logo"></a>
                <ul class="right valign-wrapper">
                    {% if user.is_authenticated %}
                    <li class="nav-link"><a href="{% url 'articles:create' %}" class="highlight">Create Post</a></li>
                        <li class="nav-link">
                            <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="waves-effect waves-light btn light-blue darken-1">Logout</button>
                            </form>
                        </li>
                    {% else %}
                        <li class="nav-link"><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li class="nav-link"><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/homepage.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the Homepage</h1>
    <p>Welcome to Diplonautic</p>
</body>
</html>